debian-configs/* /etc/icinga
debian/resource.cfg /etc/icinga
debian/conf.d/* /etc/icinga/objects
sample-config/README /usr/share/doc/icinga-common/examples
sample-config/*.cfg /usr/share/doc/icinga-common/examples
sample-config/template-object/README /usr/share/doc/icinga-common/examples/template-object
sample-config/template-object/*.cfg /usr/share/doc/icinga-common/examples/template-object
contrib/eventhandlers/* usr/share/icinga/plugins/eventhandlers
