#!/bin/sh

set -e
#set -x

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
        . /usr/share/dbconfig-common/dpkg/postrm
        dbc_go icinga-idoutils $@
fi

if [ "$1" = "purge" ]; then
	rm -f /etc/icinga/ido2db.cfg
    if which ucf >/dev/null; then
        ucf --purge /etc/icinga/ido2db.cfg
    fi
	db_purge
fi

if [ "$1" = "purge" ] ; then
	update-rc.d ido2db remove >/dev/null
fi

#DEBHELPER#

